### ISSUE TITLE
Merge into CheckStyle code?

### ISSUE THREAD

**Issue by mbert** [bjrke/JSR305CheckstylePlugin#23]
I am still using the plugin and find it useful. However integration into IDEs and build setups is a pain in the bottom. Have you tried to add your plugin to the checkstyle distribution? I think that would greatly simplify things for users.

**Comment by bjrke** [comment]
I suggest you to replace the plugin by using @ParametersAreNonnullByDefault and @ReturnValuesAreNonnullByDefault on package level and to use Optional where nulls are needed so you wont have any annotations in your code any more.
On the other hand, it is Open Source (currently GPL) but I could ask @marcust and @neurolabs if we could change to LGPL-2.1+ to allow including it into the checkstyle project.
You could also help to improve the installation process for eclipse, see issue #1

**Comment by mbert** [comment]
I do not want to eliminate the need to use annotations, because these annotations also help understanding how to use APIs etc. However having to build the plugin against the exact version of CheckStyle to use it with is tedious, and the process of integrating it into different integrated development environments (Eclipse is the easy one) is frustrating to say the least.

If the only obstacle is the license at the moment, I'd very much appreciate changing it to GPL-2.1+, so that it could be integrated into the CheckStyle project. This would also encourage more people to actually use it.

**Comment by marcust** [comment]
You can relicense it if you want, I'm ok for the parts that are attributed to me.

**Comment by bjrke** [comment]
When you have package level annotations everything is non null, except you use @Nullable or @CheckForNull. So there is no need to enforce the annotations any more. On the other hand Optional also describes if null is accepted in the form of Optional.absent() or not.

You said, that you have to build it against a special version of checkstyle. Which version are you using? Perhaps I simply missed a required update which happened in the past. But how about the other IDEs? Using the plugin in IntelliJ was not a problem (even if I currently can't remember how it was done). What are the problems in detail? What has to be done to get it fixed. You can also provide pull requests to get things fixed.

Checkstyle uses LGPL, the plugin is GPL, so it is not compatible to merge. Anyway, You have to talk to the maintainers of checkstyle if this is possible, they have to decide.

**Comment by bjrke** [comment]
Oh I have to ask @fabotronix as well.

**Comment by saittam** [comment]
I'm OK with relicensing as well, in fact I'm happy to transfer whatever copyright I may hold to whoever :)

**Comment by neurolabs** [comment]
I am also fine with relicensing (to any *GPL license) and/or waiving/transferring copyright.

**Comment by fabotronix** [comment]
I am also fine with relicensing my parts to LGPL.

**Comment by tehlers** [comment]
I have nothing against a license change and transferal of my copyrights (if there are any).
