### ISSUE TITLE
Plugin incompatible with CS 6.1?

### ISSUE THREAD

**Issue by mbert** [bjrke/JSR305CheckstylePlugin#8]
After upgrading my eclipse plugins today the plugin seems to no longer work correctly, e.g. the ParametersAreNonNullByDefault annotation is ignored now.

**Comment by bjrke** [comment]
the plugin had to be compiled for version 6.1 and then works only for this version, don't know why.
the current master is backward compatible down to 6.2 (except 6.14 and 6.16, see readme).
the test was added in https://github.com/bjrke/JSR305CheckstylePlugin/commit/935d22925b6bc00725035a64bf3acead6f281753
I will soon release a new version, to finaly fix this.
